# Generated by Django 6.0.2 on 2026-02-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_blood_group_user_city_user_is_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital_distance',
            field=models.CharField(blank=True, help_text='e.g. 2km from DHQ Hospital', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='Bahawalnagar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_donor',
            field=models.BooleanField(default=True, verbose_name='Available for Donation'),
        ),
    ]
