# Generated by Django 6.0.2 on 2026-02-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_user_bio_user_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital_distance',
            field=models.CharField(blank=True, help_text='Enter number only (e.g. 2)', max_length=200, null=True),
        ),
    ]
