# Generated by Django 6.0.2 on 2026-02-22 18:02

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_age_alter_user_hospital_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donor_id',
            field=models.CharField(blank=True, default=base.models.generate_donor_id, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
