# Generated by Django 6.0.2 on 2026-02-22 18:03

import random
import string
from django.db import migrations

def generate_unique_donor_ids(apps, schema_editor):
    User = apps.get_model('base', 'User')
    for user in User.objects.all():
        while True:
            new_id = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
            if not User.objects.filter(donor_id=new_id).exists():
                user.donor_id = new_id
                user.save(update_fields=['donor_id'])
                break

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_donor_id_user_is_suspended'),
    ]

    operations = [
        migrations.RunPython(generate_unique_donor_ids, reverse_code=migrations.RunPython.noop),
    ]
