# Generated by Django 6.0.2 on 2026-02-22 18:10

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20260222_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='donor_id',
            field=models.CharField(blank=True, default=base.models.generate_donor_id, max_length=8, null=True, unique=True),
        ),
    ]
